=== fema-ffrd/flood-data-plotter/server/api/schemas/realization_stage.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "realization_stage",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "shortname",
        "ras_element",
        "hms_element",
        "usgs_id",
        "duration",
        "interval",
        "ras_conf_limits",
        "hms_conf_limits",
        "ras_stage",
        "hms_stage",
        "ressim_stage",
        "obs_stage",
        "obs_conf_limits"
    ],
    "properties": {
        "shortname": {
            "type": "string"
        },
        "ras_element": {
            "type": "string"
        },
        "hms_element": {
            "type": "string"
        },
        "usgs_id": {
            "type": "string"
        },
        "duration": {
            "type": "integer"
        },
        "interval": {
            "type": "string"
        },
        "json": {
            "type": "boolean"
        },
        "ras_conf_limits": {
            "type": "array",
            "maxItems": 3,
            "items": {
                "type": "object",
                "required": [
                    "Z",
                    "median",
                    "p95",
                    "p05",
                    "mean"
                ],
                "additionalProperties": false,
                "properties": {
                    "Z": {
                        "type": "number"
                    },
                    "median": {
                        "type": "number"
                    },
                    "p95": {
                        "type": "number"
                    },
                    "p05": {
                        "type": "number"
                    },
                    "mean": {
                        "type": "number"
                    }
                }
            }
        },
        "hms_conf_limits": {
            "type": "array",
            "maxItems": 3,
            "items": {
                "$ref": "#/properties/ras_conf_limits/items"
            }
        },
        "ras_stage": {
            "type": "array",
            "maxItems": 3,
            "items": {
                "type": "object",
                "required": [
                    "realization",
                    "stage"
                ],
                "additionalProperties": false,
                "properties": {
                    "realization": {
                        "type": "integer"
                    },
                    "stage": {
                        "type": "array",
                        "maxItems": 3,
                        "items": {
                            "type": "object",
                            "required": [
                                "Block",
                                "Event",
                                "value",
                                "AEP",
                                "Z",
                                "RP"
                            ],
                            "additionalProperties": false,
                            "properties": {
                                "Block": {
                                    "type": "integer"
                                },
                                "Event": {
                                    "type": "integer"
                                },
                                "value": {
                                    "type": "number"
                                },
                                "AEP": {
                                    "type": "number"
                                },
                                "Z": {
                                    "type": "number"
                                },
                                "RP": {
                                    "type": "number"
                                }
                            }
                        }
                    }
                }
            }
        },
        "hms_stage": {
            "type": "array",
            "maxItems": 3,
            "items": {
                "$ref": "#/properties/ras_stage/items"
            }
        },
        "ressim_stage": {
            "type": "array",
            "maxItems": 3,
            "items": {
                "$ref": "#/properties/ras_stage/items"
            }
        },
        "obs_stage": {
            "type": "array",
            "maxItems": 3,
            "items": {
                "type": "object",
                "required": [
                    "Date",
                    "Stage",
                    "AEP",
                    "Z",
                    "RP"
                ],
                "additionalProperties": false,
                "properties": {
                    "Date": {
                        "type": "string"
                    },
                    "Stage": {
                        "type": "number"
                    },
                    "AEP": {
                        "type": "number"
                    },
                    "Z": {
                        "type": "number"
                    },
                    "RP": {
                        "type": "number"
                    }
                }
            }
        },
        "obs_conf_limits": {
            "type": "array",
            "maxItems": 3,
            "items": {
                "type": "object",
                "required": [
                    "temp_name",
                    "variable",
                    "duration",
                    "AEP",
                    "Upper",
                    "Lower",
                    "z"
                ],
                "additionalProperties": false,
                "properties": {
                    "temp_name": {
                        "type": "string"
                    },
                    "variable": {
                        "type": "string"
                    },
                    "duration": {
                        "type": "integer"
                    },
                    "AEP": {
                        "type": "number"
                    },
                    "Graphical": {
                        "type": "string"
                    },
                    "Upper": {
                        "type": "number"
                    },
                    "Lower": {
                        "type": "number"
                    },
                    "z": {
                        "type": "number"
                    }
                }
            }
        }
    }
}

=== fema-ffrd/flood-data-plotter/server/src/example-jsons/stage-example.json
{
    "shortname": "Green_200th",
    "ras_element": "200thStreet_line|Perimeter 1",
    "hms_element": "J_GRN_200THST",
    "usgs_id": "12113344",
    "duration": 1,
    "interval": "Hour",
    "json": false,
    "ras_conf_limits": [
        {
            "Z": 2.326,
            "median": 1017.8515,
            "p95": 1119.9409,
            "p05": 915.7621,
            "mean": 1017.8515
        },
        {
            "Z": 1.282,
            "median": 5467.0161,
            "p95": 5513.3654,
            "p05": 5420.6668,
            "mean": 5467.0161
        },
        {
            "Z": 0.674,
            "median": 7970.319,
            "p95": 8062.554,
            "p05": 7878.084,
            "mean": 7970.319
        }
    ],
    "hms_conf_limits": [
        {
            "Z": 2.326,
            "median": 6269.7021,
            "p95": 6551.7617,
            "p05": 5987.6425,
            "mean": 6269.7021
        },
        {
            "Z": 1.282,
            "median": 8987.4594,
            "p95": 9011.8957,
            "p05": 8963.0232,
            "mean": 8987.4594
        },
        {
            "Z": 0.674,
            "median": 10140.5654,
            "p95": 10178.0465,
            "p05": 10103.0844,
            "mean": 10140.5654
        }
    ],
    "ras_stage": [
        {
            "realization": 1,
            "stage": [
                {
                    "Block": 1,
                    "Event": 1,
                    "value": 5001,
                    "AEP": 0.05,
                    "Z": 0.9968,
                    "RP": 1.1897
                },
                {
                    "Block": 2,
                    "Event": 14,
                    "value": 5002,
                    "AEP": 0.025,
                    "Z": -0.7827,
                    "RP": 4.6106
                },
                {
                    "Block": 3,
                    "Event": 17,
                    "value": 5003,
                    "AEP": 0.01,
                    "Z": 0.1199,
                    "RP": 1.8257
                }
            ]
        },
        {
            "realization": 2,
            "stage": [
                {
                    "Block": 1,
                    "Event": 20131,
                    "value": 9433.4893,
                    "AEP": 0.5592,
                    "Z": 0.149,
                    "RP": 1.7882
                },
                {
                    "Block": 2,
                    "Event": 20149,
                    "value": 3747.9551,
                    "AEP": 0.932,
                    "Z": 1.4911,
                    "RP": 1.0729
                },
                {
                    "Block": 3,
                    "Event": 20153,
                    "value": 10873.6494,
                    "AEP": 0.035,
                    "Z": -1.8121,
                    "RP": 28.5857
                }
            ]
        }
    ],
    "hms_stage": [
        {
            "realization": 1,
            "stage": [
                {
                    "Block": 241,
                    "Event": 2486,
                    "value": 40878.1487,
                    "AEP": 0.0005,
                    "Z": -3.2907,
                    "RP": 2001
                },
                {
                    "Block": 1558,
                    "Event": 15681,
                    "value": 38749.0816,
                    "AEP": 0.001,
                    "Z": -3.0904,
                    "RP": 1000.5
                },
                {
                    "Block": 706,
                    "Event": 7201,
                    "value": 37248.7038,
                    "AEP": 0.0015,
                    "Z": -2.9679,
                    "RP": 667
                }
            ]
        },
        {
            "realization": 2,
            "stage": [
                {
                    "Block": 1277,
                    "Event": 32828,
                    "value": 57285.0842,
                    "AEP": 0.0005,
                    "Z": -3.2907,
                    "RP": 2001
                },
                {
                    "Block": 587,
                    "Event": 25914,
                    "value": 45446.0715,
                    "AEP": 0.001,
                    "Z": -3.0904,
                    "RP": 1000.5
                },
                {
                    "Block": 354,
                    "Event": 23587,
                    "value": 34401.6038,
                    "AEP": 0.0015,
                    "Z": -2.9679,
                    "RP": 667
                }
            ]
        }
    ],
    "ressim_stage": [
        {
            "realization": 1,
            "stage": [
                {
                    "Block": 1,
                    "Event": 1,
                    "value": 7731.9403,
                    "AEP": 0.917,
                    "Z": 1.3854,
                    "RP": 1.0905
                },
                {
                    "Block": 2,
                    "Event": 12,
                    "value": 11339.0724,
                    "AEP": 0.3368,
                    "Z": -0.4211,
                    "RP": 2.9688
                },
                {
                    "Block": 3,
                    "Event": 17,
                    "value": 11204.0367,
                    "AEP": 0.5012,
                    "Z": 0.0031,
                    "RP": 1.995
                }
            ]
        },
        {
            "realization": 2,
            "stage": [
                {
                    "Block": 1,
                    "Event": 20131,
                    "value": 11817.6139,
                    "AEP": 0.0765,
                    "Z": -1.4293,
                    "RP": 13.0784
                },
                {
                    "Block": 2,
                    "Event": 20147,
                    "value": 8827.521,
                    "AEP": 0.8496,
                    "Z": 1.0346,
                    "RP": 1.1771
                },
                {
                    "Block": 3,
                    "Event": 20153,
                    "value": 11619.816,
                    "AEP": 0.1409,
                    "Z": -1.0762,
                    "RP": 7.0957
                }
            ]
        }
    ],
    "obs_stage": [
        {
            "Date": "23 Feb 2012, 24:00",
            "Stage": 5001,
            "AEP": 0.3846,
            "Z": -0.2934,
            "RP": 2.6
        },
        {
            "Date": "08 Apr 2013, 24:00",
            "Stage": 5002,
            "AEP": 0.8462,
            "Z": 1.0201,
            "RP": 1.1818
        },
        {
            "Date": "11 Mar 2014, 24:00",
            "Stage": 5003,
            "AEP": 0.3077,
            "Z": -0.5024,
            "RP": 3.25
        }
    ],
    "obs_conf_limits": [
        {
            "temp_name": "200th St",
            "variable": "Stage",
            "duration": 1,
            "AEP": 0.05,
            "Graphical": "NA",
            "Upper": 11441,
            "Lower": 9017,
            "z": -1.6449
        },
        {
            "temp_name": "200th St",
            "variable": "Stage",
            "duration": 1,
            "AEP": 0.1,
            "Graphical": "NA",
            "Upper": 10757,
            "Lower": 8601,
            "z": -1.2816
        },
        {
            "temp_name": "200th St",
            "variable": "Stage",
            "duration": 1,
            "AEP": 0.2,
            "Graphical": "NA",
            "Upper": 9949,
            "Lower": 8084,
            "z": -0.8416
        }
    ]
}
